name: CI/CD

on:
  push:
    branches:
    - main

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.x

    - name: Setup Tools
      run: |
        go install go.uber.org/mock/mockgen@latest

    - name: Go Generate
      run: |
        go generate ./...

    - name: Go Test
      run: |
        go test ./...
