name: CI/CD

on:
  push:
    branches:
    - main

permissions:
  contents: write

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.x

    - name: Setup Tools
      run: |
        go install go.uber.org/mock/mockgen@latest

    - name: Go Generate
      run: |
        go generate ./...

    - name: Go Test
      run: |
        go test ./...

    - name: Get current tag
      id: get_current_tag
      run: |
        current_tag=$(git tag -l --sort=-creatordate | head -n 1)
        if [[ -z "$current_tag" ]]; then
          current_tag="v0.0.0"
        fi
        echo "current_tag=$current_tag" >> $GITHUB_OUTPUT

    - name: Get current commit type
      id: get_current_commit_type
      run: |
        commit_type=$(git show -s --format=%s | awk -F ':' '{ print $1 }')
        echo "commit_type=$commit_type" >> $GITHUB_OUTPUT

    - name: Create new tag
      id: create_new_tag
      run: |
        current_tag="${{ steps.get_current_tag.outputs.current_tag }}"
        case "${{ steps.get_current_commit_type.outputs.commit_type }}" in
          "fix")
            new_tag=$(echo "$current_tag" | awk -F 'v' '{ print $2 }' | awk -F '.' '{ print "v" $1 "." $2 "." $3+1 }')
            ;;
          "feat")
            new_tag=$(echo "$current_tag" | awk -F 'v' '{ print $2 }' | awk -F '.' '{ print "v" $1 "." $2+1 "." $3 }')
            ;;
          "BREAKING CHANGE")
            new_tag=$(echo "$current_tag" | awk -F 'v' '{ print $2 }' | awk -F '.' '{ print "v" $1+1 "." $2 "." $3 }')
            ;;
        esac
        if [[ -n "$new_tag" ]]; then
          git tag "$new_tag" main
          git push origin tag "$new_tag"
        fi
        echo "new_tag=$new_tag" >> $GITHUB_OUTPUT

    - name: Create release
      if: steps.create_new_tag.outputs.new_tag != ''
      uses: actions/create-release@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: ${{ steps.create_new_tag.outputs.new_tag }}
        draft: false
        prerelease: false
